'use client';
import Link from 'next/link';
import { SaveLeadButton } from '@/components/save-lead-button';
import { isPotentialClient, presenceLabel } from '@/lib/opportunity';
import { useEffect, useState } from 'react';
import { Search, ArrowUpRight, Plus } from 'lucide-react';
import { api, Badge, Loading, Notice, PageTitle, Score, useData } from '@/components/ui';
import { DEFAULT_EXCLUSIONS, TARGET_INDUSTRIES } from '@/lib/targeting';
import type { Campaign, Lead, SearchInput } from '@/lib/types';
import type { DiscoveryResult } from '@/lib/discovery';
export default function DiscoverPage(){
 const {data,error}=useData<{leads:Lead[]}>('/api/leads'),{data:settings}=useData<{liveDiscovery:boolean}>('/api/settings'),{data:campaigns}=useData<{campaigns:Campaign[]}>('/api/campaigns');
 const {data:savedLeads,setData:setSavedLeads}=useData<{leads:Lead[]}>('/api/saved-leads');
 const savedIds=new Set(savedLeads?.leads.map(l=>l.id));
 function refreshSaved(){api<{leads:Lead[]}>('/api/saved-leads').then(setSavedLeads).catch(e=>setFailure(e.message));}
 const [result,setResult]=useState<DiscoveryResult|null>(null),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[notice,setNotice]=useState('');
 const [locationType,setLocationType]=useState<SearchInput['locationType']>('city'),[location,setLocation]=useState('Fairfax, VA'),[industry,setIndustry]=useState('Healthcare'),[nicheId,setNicheId]=useState('home-health');
 const [excludeLarge,setExcludeLarge]=useState(true),[excludeTerms,setExcludeTerms]=useState(DEFAULT_EXCLUSIONS),[showFilters,setShowFilters]=useState(false);
 const [flagged,setFlagged]=useState(false),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(1),[campaign,setCampaign]=useState('campaign-1'),[enrolling,setEnrolling]=useState(false);
 const [saved,setSaved]=useState<SearchInput[]>([]),[showSaved,setShowSaved]=useState(false);
 useEffect(()=>{try{const rows=JSON.parse(localStorage.getItem('handos-searches')||'[]');if(Array.isArray(rows))setSaved(rows.filter(s=>['zip','city','state'].includes(s.locationType)&&typeof s.location==='string'&&TARGET_INDUSTRIES.some(i=>i.name===s.industry&&i.niches.some(n=>n.id===s.nicheId))));}catch{}},[]);
 const [restored,setRestored]=useState(false);
 useEffect(()=>{try{const state=JSON.parse(sessionStorage.getItem('handos-current-search-v2')||'null');if(state&&['zip','city','state'].includes(state.locationType)&&typeof state.location==='string'&&TARGET_INDUSTRIES.some(i=>i.name===state.industry&&i.niches.some(n=>n.id===state.nicheId))){setLocationType(state.locationType);setLocation(state.location);setIndustry(state.industry);setNicheId(state.nicheId);setExcludeLarge(state.excludeLarge!==false);setExcludeTerms(state.excludeTerms||'');setResult(state.result||null);setFlagged(!!state.flagged);setSelected(Array.isArray(state.selected)?state.selected:[]);setPage(Number.isInteger(state.page)&&state.page>0?state.page:1);setCampaign(state.campaign||'campaign-1');setShowFilters(!!state.showFilters);}}catch{}finally{setRestored(true);}},[]);
 useEffect(()=>{if(!restored)return;try{sessionStorage.setItem('handos-current-search-v2',JSON.stringify({locationType,location,industry,nicheId,excludeLarge,excludeTerms,result,flagged,selected,page,campaign,showFilters}));}catch{}},[restored,locationType,location,industry,nicheId,excludeLarge,excludeTerms,result,flagged,selected,page,campaign,showFilters]);
 function saveSearch(){const item={locationType,location,industry,nicheId,excludeLarge,excludeTerms};const next=[...saved.filter(s=>JSON.stringify(s)!==JSON.stringify(item)),item];setSaved(next);localStorage.setItem('handos-searches',JSON.stringify(next));setNotice('Search saved in this browser.');}
 const source=(data?.leads||[]).filter(l=>settings?.liveDiscovery?l.source==='serpapi':l.source==='demo');
 const qualified=result?.leads||source.filter(isPotentialClient);
 const excluded=result?.excludedLeads||[];
 const leads=(flagged?excluded:qualified).slice().sort((a,b)=>Number(selected.includes(b.id))-Number(selected.includes(a.id))||a.company.localeCompare(b.company));
 const pages=Math.max(1,Math.ceil(leads.length/8)),visible=leads.slice((page-1)*8,page*8);
 async function search(e:React.FormEvent){e.preventDefault();setBusy(true);setFailure('');setSelected([]);try{setResult(await api<DiscoveryResult>('/api/search',{locationType,location,industry,nicheId,excludeLarge,excludeTerms}));setFlagged(false);setPage(1);}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 async function enroll(){setEnrolling(true);setFailure('');let count=0;const errors:string[]=[];for(const id of selected){try{await api('/api/enroll',{leadId:id,campaignId:campaign});count++;}catch(e){errors.push((qualified.find(l=>l.id===id)?.company||id)+': '+(e as Error).message);}}setNotice(count+' lead(s) enrolled. No live email sent.');setFailure(errors.join(' '));setEnrolling(false);}
 if(!restored)return <Loading/>;
 return <>
 <PageTitle eyebrow="PROSPECTING / DISCOVERY" title="Find your next opportunity" description="Discover businesses without a website or with observed legacy website signals." action={<button className="button secondary" onClick={()=>setShowSaved(!showSaved)}>Saved searches</button>}/>
 {showSaved&&<section className="panel panel-padding"><div className="selection-toolbar"><h2>Saved searches</h2><button className="button secondary" onClick={saveSearch}>Save current search</button></div>{saved.map((s,i)=><button className="button subtle" key={i} onClick={()=>{setLocationType(s.locationType);setLocation(s.location);setIndustry(s.industry);setNicheId(s.nicheId!);setExcludeLarge(s.excludeLarge!==false);setExcludeTerms(s.excludeTerms||'');setShowSaved(false);}}>{s.location} · {s.industry} · {TARGET_INDUSTRIES.find(i=>i.name===s.industry)?.niches.find(n=>n.id===s.nicheId)?.label}</button>)}{!saved.length&&<p className="muted">Save your current location and industry to reuse them.</p>}</section>}
 <Notice>{settings?.liveDiscovery?'Live discovery · Directory-only results and legacy websites are potential clients. Other website/social results and incomplete checks stay excluded.':'Demo workspace · Fictional records. Local enrollment and reporting work; no email is sent.'}</Notice>
 <section className="discovery-panel"><form onSubmit={search}><div className="location-mode"><strong>Search by one location</strong><div className="segmented">{(['zip','city','state'] as const).map(v=><button type="button" key={v} aria-pressed={locationType===v} className={locationType===v?'selected':''} onClick={()=>{setLocationType(v);setLocation(v==='zip'?'22030':v==='state'?'VA':'Fairfax, VA');}}>{v==='zip'?'ZIP code':v==='city'?'City':'State'}</button>)}</div><small>Location AND industry · one mode at a time</small></div>
 <div className="search-form"><div className="field"><label htmlFor="location">{locationType==='city'?'City, State':locationType==='zip'?'ZIP code':'State'}</label><input id="location" value={location} required minLength={2} maxLength={100} pattern={locationType==='zip'?'[0-9]{5}':undefined} onChange={e=>setLocation(e.target.value)}/></div><div className="field"><label htmlFor="industry">Industry</label><select id="industry" value={industry} onChange={e=>{setIndustry(e.target.value);setNicheId(TARGET_INDUSTRIES.find(i=>i.name===e.target.value)!.niches[0].id);}}>{TARGET_INDUSTRIES.map(i=><option key={i.name}>{i.name}</option>)}</select></div><div className="field"><label htmlFor="niche">Business niche</label><select id="niche" value={nicheId} onChange={e=>setNicheId(e.target.value)}>{TARGET_INDUSTRIES.find(i=>i.name===industry)?.niches.map(n=><option value={n.id} key={n.id}>{n.label}</option>)}</select></div><button className="button primary" disabled={busy}><Search size={16}/>{busy?'Checking presence…':'Search leads'}</button></div><p className="search-hint">{settings?.liveDiscovery?'Checks up to 10 candidates through two identity searches each; allow several minutes.':'Demo records are in Boston. Select Boston to try a sample search.'}</p></form></section>
 <div className="stats-row">{[['Matching leads',qualified.length,'No website found or legacy website'],['Listings reviewed',result?.totalReviewed??qualified.length,location+' · '+industry],['Excluded / unverified',excluded.length,'Presence found or incomplete evidence']].map(([label,value,sub])=><div className="summary-stat" key={label}><div><p>{label}</p><strong>{value}</strong><small>{sub}</small></div></div>)}</div>
 {(failure||error)&&<Notice error>{failure||error}</Notice>}{notice&&<Notice>{notice}</Notice>}{result&&<Notice>{result.notice}</Notice>}
 <section className="panel"><div className="panel-heading"><div className="segmented"><button className={!flagged?'selected':''} onClick={()=>{setFlagged(false);setPage(1);}}>Qualified · {qualified.length}</button><button className={flagged?'selected':''} onClick={()=>{setFlagged(true);setPage(1);}}>Excluded · {excluded.length}</button></div><button className="button secondary" onClick={()=>setShowFilters(!showFilters)}>Filters</button></div>
 {showFilters&&<div className="panel-padding"><label className="check-label"><input type="checkbox" checked={excludeLarge} onChange={e=>setExcludeLarge(e.target.checked)}/>Exclude institutions, closed listings and unrelated niches on next search</label><div className="field"><label htmlFor="exclude">Excluded names or phrases</label><input id="exclude" value={excludeTerms} onChange={e=>setExcludeTerms(e.target.value)}/></div></div>}
 <div className="selection-toolbar"><strong>{selected.length} selected · Ready for an audit-first conversation</strong><div className="toolbar"><select aria-label="Destination campaign" value={campaign} onChange={e=>setCampaign(e.target.value)}>{campaigns?.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="button primary" disabled={!selected.length||enrolling} onClick={enroll}><Plus size={16}/>{enrolling?'Enrolling…':'Add to campaign'}</button></div></div>
 {!data&&!error?<Loading/>:!leads.length?<div className="empty"><Search size={28}/><h3>No qualified leads yet</h3><p>Run a search or inspect excluded results. A missing website link alone does not qualify a business.</p></div>:<div className="table-wrap"><table className="lead-table"><thead><tr><th>Select</th><th>Business / contact</th><th>Location</th><th>Web presence</th><th>Score</th><th>Audit opportunity</th><th/></tr></thead><tbody>{visible.map(l=><tr key={l.id} className={selected.includes(l.id)?'selected-row':''}><td><input type="checkbox" aria-label={'Select '+l.company} checked={selected.includes(l.id)} disabled={flagged} onChange={()=>setSelected(s=>s.includes(l.id)?s.filter(x=>x!==l.id):[...s,l.id])}/></td><td><Link href={'/leads/'+l.id}><strong>{l.company}</strong></Link><small>{l.firstName||'Contact unverified'}{l.emailCandidates?.length?' · '+l.emailCandidates.length+' email(s) found':''} · {l.source==='demo'?'Demo record':l.industry}</small></td><td>{[l.city,l.state,l.zip].filter(Boolean).join(', ')||l.listing?.address||'Unverified'}</td><td><Badge tone={l.presence?.status==='presence-found'?'blue':'amber'}>{presenceLabel(l)}</Badge></td><td><Score value={l.audit.opportunity}/></td><td>{l.presence?.reason||l.audit.findings[0]}</td><td><div className="lead-actions"><Link className="lead-open" href={'/leads/'+l.id} aria-label={'View '+l.company}><ArrowUpRight size={20}/></Link><SaveLeadButton leadId={l.id} saved={savedIds.has(l.id)} onChanged={refreshSaved}/></div></td></tr>)}</tbody></table></div>}
 <div className="table-foot"><span>{leads.length?'Showing '+((page-1)*8+1)+'–'+Math.min(page*8,leads.length)+' of '+leads.length:'0 leads'} · Scores require observed evidence</span><div className="toolbar"><button className="button secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><span>{page} / {pages}</span><button className="button secondary" disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</button></div></div></section><p className="bottom-note">Discovery listings themselves are digital traces. No additional indexed presence found is not proof of absence.</p>
 </>;
}
