import type { Lead, Variant } from './types';
export const sequence = [
 {step:1,delayDays:0,label:'Offer a fresh perspective',A:{subject:'How {{company_name}} looks to customers online',body:"Hi {{company_name}} Team,\n\nWe have prepared a complimentary, short review of how {{company_name}} appears to customers online. If useful, we would be happy to share a few practical improvements.\n\nWould you be open to a 15-minute audit walkthrough? Schedule here: https://handos.co\n\nBest,\nThe Handos team"},B:{subject:'A free digital presence review for {{company_name}}',body:"Hi {{company_name}} Team,\n\nWhen someone discovers your company, how easy is it for them to take the next step? We’d be happy to offer a free digital presence audit with a few actionable suggestions.\n\nPlease feel free to choose a time for a brief walkthrough: https://handos.co\n\nBest,\nThe Handos team"}},
 {step:2,delayDays:3,label:'Explore the intake experience',A:{subject:'A quick question about intake at {{company_name}}',body:'Hi {{first_name}},\n\nFollowing up on the free audit: how do new clients or members share their details with {{company_name}}? We can review the intake experience and spot places where people may drop off or need extra help.\n\nWould a short walkthrough help? https://handos.co\n\nBest,\nThe Handos team'},B:{subject:'From first inquiry to next step at {{company_name}}',body:'Hi {{first_name}},\n\nIs it easy to follow an inquiry from first contact to a completed registration at {{company_name}}? Our free review can highlight simple ways to make that journey clearer for both visitors and your team.\n\nBook a brief audit walkthrough: https://handos.co\n\nBest,\nThe Handos team'}},
 {step:3,delayDays:7,label:'Close with workflow value',A:{subject:'One place to follow up at {{company_name}}',body:'Hi {{first_name}},\n\nOne last note: how does {{company_name}} keep track of inquiries, intake responses, and follow-ups? A free review could help identify whether a centralized view would save your team time.\n\nIf useful, schedule an audit walkthrough: https://handos.co\n\nIf now isn’t a good time, no problem.\n\nBest,\nThe Handos team'},B:{subject:'Should I close the loop, {{first_name}}?',body:'Hi {{first_name}},\n\nI’ll close the loop after this. If {{company_name}} is reviewing how it manages client or member responses, I can offer a free audit and a few practical ideas for keeping follow-ups organized.\n\nYou’re welcome to choose a time here: https://handos.co\n\nThanks for considering it,\nThe Handos team'}}
] as const;
export function personalize(text:string,lead:Pick<Lead,'firstName'|'company'>) {return text.replaceAll('{{first_name}}',lead.firstName || 'there').replaceAll('{{company_name}}',lead.company);}
export function renderMessage(step:number, variant:Variant, lead:Lead, templates:readonly {A:{subject:string;body:string};B:{subject:string;body:string}}[]=sequence) {
 const template=templates[step-1][variant];
 return {subject:personalize(template.subject,lead),body:personalize(template.body,lead)};
}
