'use client';
import { useEffect, useState } from 'react';
import { api, Badge, Loading, Notice, PageTitle, useData } from '@/components/ui';
import { personalize } from '@/lib/sequence';
import type { Campaign } from '@/lib/types';
import type { CampaignSequence } from '@/lib/campaign-sequence';
export default function Sequences(){
 const {data:campaigns}=useData<{campaigns:Campaign[]}>('/api/campaigns');
 const [campaign,setCampaign]=useState('campaign-1'),[draft,setDraft]=useState<CampaignSequence|null>(null),[failure,setFailure]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{let active=true;setDraft(null);setDirty(false);api<{sequence:CampaignSequence}>('/api/campaigns/'+campaign+'/sequence').then(r=>{if(active){setDraft(r.sequence);setFailure('');}}).catch(e=>{if(active)setFailure(e.message);});return()=>{active=false;};},[campaign]);
 function edit(index:number,variant:'A'|'B',key:'subject'|'body',value:string){setDirty(true);setDraft(d=>d?.map((s,i)=>i===index?{...s,[variant]:{...s[variant],[key]:value}}:s)||null);}
 async function save(){setBusy(true);setFailure('');try{const r=await api<{notice:string}>('/api/campaigns/'+campaign+'/sequence',draft);setNotice(r.notice);setDirty(false);}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 return <><PageTitle eyebrow="SEQUENCES / AUDIT-FIRST OUTREACH" title="Digital experience review" description="Three personalized, audit-first emails. A consultative conversation with a useful next step." action={<div className="toolbar"><button className="button secondary" onClick={()=>setPreview(!preview)}>{preview?'Edit templates':'Preview'}</button><button className="button primary" disabled={!draft||busy} onClick={save}>{busy?'Saving…':'Save draft'}</button></div>}/>
 <Notice>Templates are saved to the backend and used for future demo and live messages. Live delivery requires configured and enabled SendGrid settings.</Notice>
 {failure&&<Notice error>{failure}</Notice>}{notice&&<Notice>{notice}</Notice>}
 <section className="panel sequence-toolbar"><label htmlFor="sequence-campaign">Campaign</label><select id="sequence-campaign" value={campaign} onChange={e=>{if(!dirty||window.confirm('Discard unsaved template changes?')){setCampaign(e.target.value);setNotice('');}}}>{campaigns?.campaigns.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><Badge>{dirty?'Unsaved changes':'Saved'}</Badge><span className="muted">3 steps · Day 0, 3, 7 · {'{{first_name}}'} · {'{{company_name}}'}</span></section>
 {!draft?<Loading/>:draft.map((s,index)=><section className="panel sequence-editor-step" key={s.step}><header><span className="sequence-number">{String(s.step).padStart(2,'0')}</span><div><h2>{s.label}</h2><p className="muted">Start with a useful question, then offer a free audit.</p></div><small>Day {s.delayDays}</small></header><div className="sequence-variants">{(['A','B'] as const).map(v=><article className="sequence-variant" key={v}><Badge tone={v==='A'?'blue':'amber'}>Variant {v}</Badge>{preview?<div className="email-preview"><strong>{personalize(s[v].subject,{firstName:'Alex',company:'Example business'})}</strong><p>{personalize(s[v].body,{firstName:'Alex',company:'Example business'})}</p></div>:<><label htmlFor={'subject-'+s.step+v}>SUBJECT</label><input id={'subject-'+s.step+v} maxLength={200} value={s[v].subject} onChange={e=>edit(index,v,'subject',e.target.value)}/><label htmlFor={'body-'+s.step+v}>MESSAGE</label><textarea id={'body-'+s.step+v} maxLength={6000} value={s[v].body} onChange={e=>edit(index,v,'body',e.target.value)}/></>}</article>)}</div></section>)}
 <section className="panel panel-padding"><h2>Enrollment & stopping rules</h2><p className="muted">Recipients keep their assigned A/B variant. Replies, bounces, unsubscribes and booked demos stop follow-ups across campaigns. Every template requires a handos.co scheduling link. Existing sent messages stay unchanged.</p></section></>;
}
