'use client';
import Link from 'next/link';
import { SaveLeadButton } from '@/components/save-lead-button';
import { presenceLabel } from '@/lib/opportunity';
import { use, useState } from 'react';
import { ArrowLeft, Globe, Mail, MapPin, Check, Send, CalendarClock, FlaskConical } from 'lucide-react';
import { api, Badge, Loading, Notice, PageTitle, Score, useData } from '@/components/ui';
import { QualificationPanel } from '@/components/qualification';
import { ContactEditor } from '@/components/contact-editor';
import { LeadOutcome } from '@/components/lead-outcome';
import { renderMessage } from '@/lib/sequence';
import type { Campaign, Enrollment, EventType, Lead, Message, TrackingEvent, Variant } from '@/lib/types';
import type { CampaignSequence } from '@/lib/campaign-sequence';
type Detail={deliveries:{messageId:string;status:string}[];lead:Lead;enrollments:Enrollment[];messages:Message[];events:TrackingEvent[];campaigns:Campaign[]};
export default function LeadDetail({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const {data,error,setData}=useData<Detail>(`/api/leads/${id}`);const [campaign,setCampaign]=useState('campaign-1'),[variant,setVariant]=useState<Variant>('A'),[step,setStep]=useState(1),[notice,setNotice]=useState(''),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false),[eventType,setEventType]=useState<EventType>('open');
 async function action(url:string,body:unknown){setBusy(true);setFailure('');try{const result=await api<{notice?:string}>(url,body);setNotice(result.notice||(url==='/api/enroll'?'Lead enrolled. No email has been sent yet.':'Saved successfully.'));setData(await api<Detail>(`/api/leads/${id}`));}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 const {data:settings}=useData<{email:{provider:string;ready:boolean;enabled:boolean}}>('/api/settings');
 const live=settings?.email.provider==='sendgrid';
 const {data:saved,setData:setSaved}=useData<{leads:Lead[]}>('/api/saved-leads');
 const refreshSaved=()=>{api<{leads:Lead[]}>('/api/saved-leads').then(setSaved).catch(e=>setFailure(e.message));};
 const {data:sequenceData}=useData<{sequence:CampaignSequence}>(`/api/campaigns/${campaign}/sequence`);
 if(error)return <Notice error>{error}</Notice>;if(!data)return <Loading/>;const {lead,enrollments,messages,events,campaigns}=data;const preview=renderMessage(step,variant,lead,sequenceData?.sequence);const latest=[...messages].sort((a,b)=>b.sentAt.localeCompare(a.sentAt))[0];
 return <><Link className="back-link" href="/"><ArrowLeft size={16}/>Back to discovery</Link><PageTitle eyebrow="LEAD PROFILE" title={lead.company} description={`${lead.industry} · ${lead.listing?.address||[lead.city,lead.state,lead.zip].filter(Boolean).join(', ')}`} action={<div className="toolbar"><SaveLeadButton leadId={id} saved={!!saved?.leads.some(l=>l.id===id)} onChanged={refreshSaved}/><Badge tone="purple">{lead.source==='demo'?'Fictional demo lead':'Live discovery · unverified'}</Badge></div>}/>{notice&&<Notice>{notice}</Notice>}{failure&&<Notice error>{failure}</Notice>}<div className="detail-grid"><div>
 {lead.presence&&<section className="panel panel-padding presence-evidence"><h2>Independent digital presence checks</h2><Badge tone={lead.presence.status==='presence-found'?'blue':'amber'}>{presenceLabel(lead)}</Badge><p style={{marginTop:12}}>{lead.presence.reason.includes('verification limit reached')?'Awaiting presence checks; this listing was beyond the initial 10-candidate check limit.':lead.presence.reason}</p><button className="button secondary" disabled={busy} onClick={()=>action('/api/leads/'+id+'/presence-check',{})}>{busy?'Checking…':'Run presence check for this lead'}</button><small>Last assessment {new Date(lead.presence.checkedAt).toLocaleString()}</small><h3 style={{marginTop:16}}>Identity searches</h3>{!lead.presence.queries.length&&<p className="fine-print">No identity searches have run. A listed website may be used directly; otherwise independent checks require the listing’s address and phone.</p>}<ul>{lead.presence.queries.map(q=><li key={q}>{q}</li>)}</ul>{!!lead.presence.traces.length&&<><h3>Found traces</h3><ul>{lead.presence.traces.map(t=><li key={t.url}><Badge>{t.kind}</Badge> <a href={t.url} target="_blank" rel="noreferrer">{t.title||t.url} ↗</a></li>)}</ul></>}</section>}
 <QualificationPanel lead={lead} busy={busy} onSave={value=>action(`/api/leads/${id}/readiness`,value)}/>
 <section className="panel"><div className="panel-heading"><div><h2>Digital opportunity audit</h2><p>Health scores: higher is better. Opportunity score: higher means more room to improve.</p></div></div><div className="audit-scores">{[['Digital presence',lead.audit.presence],['Conversion journey',lead.audit.conversion],['Intake & workflow',lead.audit.workflow]].map(([label,score])=><div key={label as string}><div><span>{label}</span><strong>{score??'—'}<small>/100</small></strong></div><div className="meter"><span style={{width:`${score??0}%`}}/></div></div>)}</div><div className="panel-padding findings"><h3>What the evidence suggests</h3>{lead.audit.findings.map(f=><p key={f}><Check size={17}/>{f}</p>)}<div className="evidence-note"><FlaskConical size={18}/><span>{lead.source==='demo'?'These findings come from seeded demonstration signals, not a live website inspection.':'Audit scores remain evidence-based; missing signals are not observed gaps. Use contact verification before enrolling.'}<small>Assessed {new Date(lead.audit.assessedAt).toLocaleDateString()}</small></span></div></div></section>
 <section className="panel"><div className="panel-heading"><div><h2>Activity timeline</h2><p>Messages and tracked responses for this lead.</p></div></div><div className="timeline">{!messages.length?<p className="muted">No emails yet. Enroll this lead or send the first outreach email below.</p>:messages.map(m=><div className="timeline-item" key={m.id}><span className="timeline-dot"/><div><strong>Step {m.step} · {m.subject}</strong><small>{new Date(m.sentAt).toLocaleString()} · Variant {m.variant}</small><div className="badge-list"><Badge tone={events.some(e=>e.messageId===m.id&&e.type==='bounce')?'red':events.some(e=>e.messageId===m.id&&e.type==='delivered')?'green':'amber'}>{events.some(e=>e.messageId===m.id&&e.type==='bounce')?'Bounced':events.some(e=>e.messageId===m.id&&e.type==='delivered')?'Delivered':lead.source==='demo'?'Simulated':(data.deliveries?.find(d=>d.messageId===m.id)?.status==='accepted'?'Sent · delivery pending':data.deliveries?.find(d=>d.messageId===m.id)?.status||'Unknown attempt')}</Badge>{events.filter(e=>e.messageId===m.id).map(e=><Badge key={e.id} tone={e.type==='booked-demo'?'green':'neutral'}>{e.type}</Badge>)}</div></div></div>)}</div></section></div>
 <div><section className="panel contact-panel"><div className="panel-heading"><h2>Business overview</h2><Score value={lead.audit.opportunity}/></div><div className="contact-list"><p><MapPin size={17}/>{lead.listing?.address||[lead.city,lead.state,lead.zip].filter(Boolean).join(', ')||'Location details need verification'}</p><p><Globe size={17}/>{lead.website?<a href={lead.website} target="_blank" rel="noreferrer">{lead.website.replace(/^https?:\/\//,'')}</a>:lead.audit.classification==='No website'?'No website in supplied evidence':'Website not yet verified'}</p><p><Mail size={17}/>{lead.email||'Contact email not yet verified'}</p></div><div className="panel-padding"><Badge tone="amber">{lead.audit.classification}</Badge></div></section><ContactEditor lead={lead} onSaved={()=>{api<Detail>(`/api/leads/${id}`).then(setData).catch(e=>setFailure(e.message));}}/><section className="panel enrollment-panel"><div className="panel-heading"><div><h2>Start a useful conversation</h2><p>Offer a free audit, then follow up thoughtfully.</p></div></div><div className="panel-padding"><label htmlFor="campaign-select">Choose campaign</label><select id="campaign-select" value={campaign} onChange={e=>setCampaign(e.target.value)}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="button primary full" disabled={busy||!lead.email||enrollments.some(e=>e.campaignId===campaign)} onClick={()=>action('/api/enroll',{leadId:id,campaignId:campaign})}><Send size={16}/>{enrollments.some(e=>e.campaignId===campaign)?'Already enrolled':'Enroll in campaign'}</button><p className="fine-print">Variant assigned automatically. Follow-ups at day 3 and day 7. Replies, bounces, opt-outs, and bookings stop the sequence.</p>{enrollments.map(e=><div className="enrollment" key={e.id}><strong>{campaigns.find(c=>c.id===e.campaignId)?.name}</strong><div><Badge tone={e.status==='active'?'green':'neutral'}>{e.status}</Badge><Badge>Variant {e.variant}</Badge></div>{e.status==='active'&&<small><CalendarClock size={14}/>Step {e.nextStep} due {new Date(e.nextDueAt).toLocaleString()}</small>}</div>)}<button className="button secondary full" disabled={busy||!lead.email||!settings||(live&&(!settings.email.ready||!settings.email.enabled))} onClick={()=>action('/api/leads/'+id+'/send',{campaignId:campaign})}>{busy?'Processing…':live?'Send due outreach to this prospect':'Simulate outreach to this prospect'}</button><p className="fine-print">Live sending requires a verified contact. Acceptance is shown immediately; confirmed delivery updates in the timeline.</p><Link className="button subtle" href="/analytics">View outreach analytics</Link></div></section>
 <section className="panel"><div className="panel-heading"><h2>Personalized preview</h2><div className="segmented">{(['A','B'] as Variant[]).map(v=><button key={v} className={variant===v?'selected':''} onClick={()=>setVariant(v)} aria-pressed={variant===v}>{v}</button>)}</div></div><div className="step-tabs">{[1,2,3].map(s=><button key={s} onClick={()=>setStep(s)} className={step===s?'selected':''} aria-pressed={step===s} aria-label={'Preview step '+s}><span>Step</span><span className="preview-step-circle">{s}</span></button>)}</div><div className="email-preview"><small>SUBJECT</small><strong>{preview.subject}</strong><p>{preview.body}</p></div></section>
 {latest&&<LeadOutcome leadId={id} onSaved={()=>{api<Detail>(`/api/leads/${id}`).then(setData).catch(e=>setFailure(e.message));}}/>}
 {latest&&lead.source==='demo'&&<section className="panel"><div className="panel-heading"><h2>Simulate a response</h2><FlaskConical size={18}/></div><div className="panel-padding"><p className="muted">Add an event to the latest demo message and watch analytics update.</p><label htmlFor="event-type">Response event</label><select id="event-type" value={eventType} onChange={e=>setEventType(e.target.value as EventType)}>{['open','click','reply','bounce','unsubscribe','booked-demo'].map(e=><option key={e}>{e}</option>)}</select><button className="button secondary full" disabled={busy} onClick={()=>action('/api/demo/events',{messageId:latest.id,type:eventType,externalId:crypto.randomUUID(),revenue:0})}>Record demo event</button></div></section>}</div></div></>;
}
