'use client';
import { isPotentialClient } from '@/lib/opportunity';
import Link from 'next/link';
import { useState } from 'react';
import { Play, Plus } from 'lucide-react';
import { api, Badge, Loading, Notice, PageTitle, useData } from '@/components/ui';
import type { Campaign, Enrollment, Lead, Variant } from '@/lib/types';
import type { analytics } from '@/lib/analytics';
import { DeliveryReview } from '@/components/delivery-review';
type Detail=Campaign&{enrollments:Enrollment[];experiment:{variants:{variant:Variant;delivered:number;opened:number;rate:number}[];winner:Variant|null;policy:string}};
export default function Campaigns(){
 const {data,error,setData}=useData<{campaigns:Detail[]}>('/api/campaigns');
 const {data:settings}=useData<{email:{provider:string;enabled:boolean;ready:boolean;missing:string[]}}>('/api/settings');
 const {data:leads}=useData<{leads:Lead[]}>('/api/leads?includeHistorical=1');
 const [selected,setSelected]=useState('campaign-1'),[leadId,setLeadId]=useState(''),[notice,setNotice]=useState(''),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false);
 const {data:stats}=useData<ReturnType<typeof analytics>>('/api/analytics?campaignId='+encodeURIComponent(selected));
 const campaign=data?.campaigns.find(c=>c.id===selected),m=stats?.metrics;
 const eligible=leads?.leads.filter(l=>isPotentialClient(l)&&!campaign?.enrollments.some(e=>e.leadId===l.id))||[];
 async function action(url:string,body:unknown){setBusy(true);setFailure('');try{const r=await api<{notice?:string}>(url,body);setNotice(r.notice||'Lead enrolled. No live email was sent.');setData(await api('/api/campaigns'));setLeadId('');}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 return <><PageTitle eyebrow="CAMPAIGNS / OUTREACH" title={campaign?.name||'Campaign overview'} description="Start with the finding. Offer a free audit, then follow up thoughtfully." action={<Link className="button secondary" href="/sequences">Edit sequence</Link>}/>
 <Notice>Campaign records and enrollments are stored in the backend. The demo button only simulates delivery; configured live outreach runs through the authenticated scheduler.</Notice>
 {(error||failure)&&<Notice error>{error||failure}</Notice>}{notice&&<Notice>{notice}</Notice>}
 <div className="field" style={{marginBottom:24}}><label htmlFor="campaign">Campaign</label><select id="campaign" value={selected} onChange={e=>setSelected(e.target.value)}>{data?.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
 {!data?<Loading/>:<><div className="metric-grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))'}}>{[['Enrolled leads',campaign?.enrollments.length||0],['Delivered',m?.delivered||0],['Replies',m?.reply||0],['Booked consultations',m?.booked||0]].map(([label,value])=><div className="metric-card" key={label}><div>{label}</div><strong>{value}</strong></div>)}</div>
 <div className="campaign-layout"><div><section className="panel panel-padding"><div className="selection-toolbar" style={{background:'transparent',padding:0}}><h2>Sequence status</h2><Badge>{settings?.email.provider==='sendgrid'?'SendGrid queue':'Demo sending'}</Badge></div><p style={{margin:'16px 0'}}>3 consultative emails · Automatic A/B allocation</p><div className="stats-row">{[['Share the audit','Day 0'],['Explore intake','Day 3'],['Offer a review','Day 7']].map(([label,day],i)=><div className="summary-stat" key={day}><Badge tone="blue">{String(i+1).padStart(2,'0')}</Badge><h3 style={{margin:'10px 0'}}>{label}</h3><small>{day}</small></div>)}</div><button className="button primary" disabled={busy} onClick={()=>action('/api/demo/run',{campaignId:selected})}><Play size={16}/>{busy?'Processing…':'Run due demo messages'}</button></section>
 <section className="panel"><div className="panel-heading"><h2>Enrolled leads</h2><Badge>{campaign?.enrollments.length||0}</Badge></div><div className="table-wrap"><table><thead><tr><th>Business / contact</th><th>Status</th><th>Sequence progress</th><th>Variant</th></tr></thead><tbody>{campaign?.enrollments.map(e=>{const l=leads?.leads.find(l=>l.id===e.leadId);return <tr key={e.id}><td><Link href={'/leads/'+e.leadId}><strong>{l?.company||e.leadId}</strong></Link><small>{l?.firstName||'Contact unverified'}</small></td><td><Badge>{e.status}</Badge></td><td>{e.status==='active'?'Step '+e.nextStep+' · Due '+new Date(e.nextDueAt).toLocaleDateString():'Stopped / completed'}</td><td>{e.variant}</td></tr>;})}</tbody></table>{!campaign?.enrollments.length&&<div className="empty">No leads enrolled yet.</div>}</div></section></div>
 <div><section className="panel panel-padding"><h2>Add a qualified lead</h2><p className="muted" style={{margin:'12px 0'}}>A verified email is required. Missing contact data is never fabricated.</p><div className="field"><label htmlFor="enroll-lead">Lead</label><select id="enroll-lead" value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Choose a lead</option>{eligible.map(l=><option key={l.id} value={l.id}>{l.company}{!l.email?' · Email required':''}</option>)}</select></div><button className="button primary full" disabled={!leadId||busy} onClick={()=>action('/api/enroll',{leadId,campaignId:selected})}><Plus size={16}/>Add to enrollment queue</button></section>
 <section className="panel panel-padding"><h2>Automatic experiment</h2>{campaign?.experiment.variants.map(v=><div className="ab-variant" key={v.variant}><div><Badge tone="blue">Variant {v.variant}</Badge><strong>{(v.rate*100).toFixed(1)}%</strong></div><small>{v.opened} opens / {v.delivered} delivered</small></div>)}<p className="muted">{campaign?.experiment.policy}</p><small>This is an open-rate allocation heuristic, not a statistical significance test.</small></section>
 <section className="panel panel-padding"><h2>Sending configuration</h2><p className="muted">Email provider · {settings?.email.provider||'demo'} · {settings?.email.enabled&&settings.email.ready?'Live enabled':'Live paused'}</p>{settings?.email.provider==='sendgrid'&&!!settings.email.missing.length&&<p className="fine-print">Missing: {settings.email.missing.join(', ')}</p>}<p className="fine-print">Recorded replies, bounces, opt-outs and demo bookings stop sequences across campaigns.</p></section></div></div>
 <section className="panel panel-padding"><h2>Event model</h2><div className="stats-row" style={{gridTemplateColumns:'repeat(auto-fit,minmax(100px,1fr))',marginTop:16}}>{[['Delivered',m?.delivered],['Open',m?.open],['Click',m?.click],['Reply',m?.reply],['Bounce',m?.bounce],['Unsubscribe',m?.unsubscribe],['Booked-demo',m?.booked]].map(([label,value])=><div key={label} className="summary-stat"><p>{label}</p><strong>{value||0}</strong></div>)}</div></section></>}
 <DeliveryReview/></>;
}
