'use client';
import { sendNotice, type SendResult } from '@/lib/delivery-feedback';
import { BulkContacts } from '@/components/bulk-contacts';
import { ManualLeadForm } from '@/components/manual-lead-form';
import Link from 'next/link';
import { useState } from 'react';
import { FolderHeart } from 'lucide-react';
import { api, Badge, Loading, Notice, PageTitle, useData } from '@/components/ui';
import { SaveLeadButton } from '@/components/save-lead-button';
import { presenceLabel } from '@/lib/opportunity';
import { renderMessage } from '@/lib/sequence';
import type { CampaignSequence } from '@/lib/campaign-sequence';
import type { Campaign, Lead } from '@/lib/types';
type Saved={leads:(Lead&{savedAt:string})[]};
export default function SavedLeads(){
 const {data,error,setData}=useData<Saved>('/api/saved-leads');
 const [adding,setAdding]=useState(false);
 const [query,setQuery]=useState(''),[industry,setIndustry]=useState('All industries'),[failure,setFailure]=useState('');
 const {data:campaigns}=useData<{campaigns:Campaign[]}>('/api/campaigns');
 const {data:settings}=useData<{email:{provider:string;ready:boolean;enabled:boolean}}>('/api/settings');
 const [selected,setSelected]=useState<string[]>([]),[campaign,setCampaign]=useState('campaign-1'),[busy,setBusy]=useState(false),[review,setReview]=useState(false),[notice,setNotice]=useState(''),[results,setResults]=useState<{leadId:string;enrollmentId?:string;status?:string;error?:string}[]>([]);
 const {data:deliveryStats}=useData<{metrics:{sent:number;delivered:number};attemptCounts:{pending:number;unknown:number;rejected:number};outcomes:{messageId:string;company:string;status:string;sentAt:string}[]}>('/api/analytics?source=live&campaignId='+encodeURIComponent(campaign));
 const {data:templates}=useData<{sequence:CampaignSequence}>('/api/campaigns/'+campaign+'/sequence');
 const chosen=(data?.leads||[]).filter(l=>selected.includes(l.id));
 const live=settings?.email.provider==='sendgrid';
 const preview=chosen[0]&&renderMessage(1,'A',chosen[0],templates?.sequence);
 async function launch(action:'queue'|'send'){
  setBusy(true);setFailure('');setNotice('');try{const collected:typeof results=[];let summary='';const totals:SendResult={accepted:0,failed:0,unknown:0,skipped:0,sandbox:0,sent:0,scheduled:0,mode:live?'sendgrid':'demo'};for(let i=0;i<chosen.length;i+=100){const response=await api<{results:typeof results;notice:string;delivery?:SendResult}>('/api/saved-leads/campaign',{leadIds:chosen.slice(i,i+100).map(l=>l.id),campaignId:campaign,action,bulkApproval:true});collected.push(...response.results);setResults([...collected]);if(response.delivery){for(const key of ['accepted','failed','unknown','skipped','sandbox','sent','scheduled'] as const)totals[key]=(totals[key]||0)+(response.delivery[key]||0);}if(response.delivery?.nextDueAt&&(!totals.nextDueAt||response.delivery.nextDueAt<totals.nextDueAt))totals.nextDueAt=response.delivery.nextDueAt;summary=response.notice;}const blocked=collected.filter(r=>r.error).map(r=>(chosen.find(l=>l.id===r.leadId)?.company||r.leadId)+': '+r.error);setNotice((action==='send'?sendNotice(totals):summary)+(blocked.length?' Blocked: '+blocked.slice(0,5).join(' · ')+(blocked.length>5?' · See remaining per-lead results below.':''):''));setReview(false);}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}
 }
 const leads=(data?.leads||[]).filter(l=>(industry==='All industries'||l.industry===industry)&&[l.company,l.city,l.state,l.listing?.address,l.email].filter(Boolean).join(' ').toLowerCase().includes(query.toLowerCase()));
 function refresh(){api<Saved>('/api/saved-leads').then(setData).catch(e=>setFailure(e.message));}
 return <><PageTitle eyebrow="PROSPECTING / SAVED LEADS" title="Saved leads" description="Your shortlist for later outreach. Select a shortlist for a personalized campaign, or open a lead to reach out individually." action={<div className="toolbar"><button className="button primary" disabled={busy} onClick={()=>setAdding(true)}>Add lead manually</button><Link href="/" className="button secondary">Find more leads</Link></div>}/>{(error||failure)&&<Notice error>{error||failure}</Notice>}
 {notice&&<Notice>{notice} <Link href="/analytics">View outreach analytics →</Link></Notice>}
 {adding&&<ManualLeadForm onCancel={()=>setAdding(false)} onSaved={()=>{setAdding(false);refresh();setNotice("Lead added to saved leads.");}}/>}
 {!!chosen.length&&<BulkContacts leads={chosen} onBusy={setBusy} onUpdated={updated=>{setData(current=>current?{leads:current.leads.map(l=>({...l,...updated.find(u=>u.id===l.id)}))}:current);setReview(false);}}/>}
 <section className="panel panel-padding"><h2>Personalized campaign</h2>
 {live&&deliveryStats&&<div role="status" className="notice"><strong>{deliveryStats.metrics.sent} email(s) successfully submitted to SendGrid · {deliveryStats.metrics.delivered} confirmed delivered.</strong><p>{deliveryStats.attemptCounts.pending} awaiting delivery confirmation · {deliveryStats.attemptCounts.rejected} rejected · {deliveryStats.attemptCounts.unknown} uncertain.</p>{deliveryStats.outcomes[0]&&<p>Latest: {deliveryStats.outcomes[0].company} · {deliveryStats.outcomes[0].status==='accepted'?'Submitted · delivery pending':deliveryStats.outcomes[0].status} · {new Date(deliveryStats.outcomes[0].sentAt).toLocaleString()}</p>}<Link href="/analytics">View outreach analytics →</Link></div>}
<p className="muted" style={{margin:'10px 0'}}>Each recipient receives an individual message with {'{{first_name}}'} and {'{{company_name}}'} filled from their lead record. A/B variants are assigned automatically.</p><div className="toolbar saved-campaign-controls"><label htmlFor="saved-campaign">Campaign</label><select id="saved-campaign" value={campaign} disabled={busy} onChange={e=>{setCampaign(e.target.value);setReview(false);}} style={{maxWidth:360}}>{campaigns?.campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Link className="button secondary" href="/sequences">Edit dynamic templates</Link><button className="button secondary" disabled={!leads.length||busy} onClick={()=>{setSelected(leads.map(l=>l.id));setReview(false);}}>Select all filtered leads</button><button className="button subtle" disabled={busy} onClick={()=>{setSelected([]);setReview(false);}}>Clear selection</button></div><p style={{margin:'14px 0'}}>{chosen.length} selected · {live?'SendGrid':'Demo simulation'}</p><div className="toolbar"><button className="button secondary" disabled={!chosen.length||busy} onClick={()=>launch('queue')}>Queue selected for outreach</button><button className="button primary" disabled={!chosen.length||busy||!settings||!!live&&(!settings.email.ready||!settings.email.enabled)} onClick={()=>setReview(true)}>Review &amp; {live?'send':'simulate'} selected</button></div><small>Queueing or sending approves your selected leads together using email-format validation. Individual approval and Hunter verification are optional for this batch. Invalid or suppressed contacts are skipped with a reason. The send action processes due steps only, subject to the configured batch limit.</small>
 {review&&preview&&<div className="email-preview" style={{marginTop:20}}><h3>Review {chosen.length} recipients</h3><p>Example: {chosen[0].company} · {chosen[0].email||'No email'} · Variant A. Each recipient uses their own contact details and assigned variant.</p><strong>{preview.subject}</strong><p>{preview.body}</p><div className="toolbar"><button className="button primary" disabled={busy} onClick={()=>launch('send')}>{busy?'Processing…':live?'Send due emails to selected leads':'Simulate selected messages'}</button><button className="button secondary" disabled={busy} onClick={()=>setReview(false)}>Cancel</button></div></div>}
 {!!results.length&&<ul>{results.map(r=><li key={r.leadId}>{data?.leads.find(l=>l.id===r.leadId)?.company||r.leadId}: {r.error||'Enrolled · '+r.status}</li>)}</ul>}
 </section>
 <div className="filter-bar"><div className="field"><label htmlFor="saved-query">Search saved leads</label><input id="saved-query" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Business, location or email"/></div><div className="field"><label htmlFor="saved-industry">Industry</label><select id="saved-industry" value={industry} onChange={e=>setIndustry(e.target.value)}><option>All industries</option>{[...new Set(data?.leads.map(l=>l.industry))].sort().map(i=><option key={i}>{i}</option>)}</select></div></div>
 {!data&&!error?<Loading/>:<section className="panel"><div className="panel-heading"><h2>{leads.length} saved lead(s)</h2></div>{!leads.length?<div className="empty"><FolderHeart size={28}/><h3>{data?.leads.length?'No matching saved leads':'Your shortlist is empty'}</h3><p>Use “Save for later” on search results or a lead profile.</p></div>:<div className="table-wrap"><table className="saved-lead-table"><thead><tr><th><input type="checkbox" aria-label="Select all filtered saved leads" disabled={busy||!leads.length} checked={!!leads.length&&leads.every(l=>selected.includes(l.id))} onChange={e=>{setSelected(e.target.checked?leads.map(l=>l.id):[]);setReview(false);}}/></th><th>Business</th><th>Location</th><th>Opportunity</th><th>Contact</th><th>Saved</th><th/></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><input type="checkbox" aria-label={'Select '+l.company} checked={selected.includes(l.id)} disabled={busy} onChange={()=>{setSelected(s=>s.includes(l.id)?s.filter(id=>id!==l.id):[...s,l.id]);setReview(false);}}/></td><td><Link href={'/leads/'+l.id}><strong>{l.company}</strong></Link><small>{l.industry}</small></td><td>{l.listing?.address||[l.city,l.state,l.zip].filter(Boolean).join(', ')}</td><td><Badge>{presenceLabel(l)}</Badge></td><td>{l.email||l.emailCandidates?.[0]?.email||<Badge tone="red">Missing email</Badge>}{!l.email&&!!l.emailCandidates?.length&&<small>Found · verify on lead profile</small>}</td><td>{new Date(l.savedAt).toLocaleDateString()}</td><td><SaveLeadButton leadId={l.id} saved onChanged={refresh}/></td></tr>)}</tbody></table></div>}</section>}</>;
}
